[versions]
aesthetics = "0.0.80"
foundation = "1.4.11"

[libraries]
expect-core = { module = "tz.co.asoft:expect-core", version.ref = "foundation" }
expect-coroutines = { module = "tz.co.asoft:expect-coroutines", version.ref = "foundation" }

[plugins]
applikation = { id = "tz.co.asoft.applikation", version.ref = "foundation" }
library = { id = "tz.co.asoft.library", version.ref = "foundation" }